//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACUnlockComb
    {
        public short UnlockCombID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Group01 { get; set; }
        public Nullable<short> Group02 { get; set; }
        public Nullable<short> Group03 { get; set; }
        public Nullable<short> Group04 { get; set; }
        public Nullable<short> Group05 { get; set; }
    }
}
