//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKINOUT
    {
        public int USERID { get; set; }
        public System.DateTime CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<int> VERIFYCODE { get; set; }
        public string SENSORID { get; set; }
        public string Memoinfo { get; set; }
        public Nullable<int> WorkCode { get; set; }
        public string sn { get; set; }
        public Nullable<short> UserExtFmt { get; set; }
    }
}
