//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKEXACT
    {
        public int EXACTID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<short> ISADD { get; set; }
        public string YUYIN { get; set; }
        public Nullable<short> ISMODIFY { get; set; }
        public Nullable<short> ISDELETE { get; set; }
        public Nullable<short> INCOUNT { get; set; }
        public Nullable<short> ISCOUNT { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
