//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmOpLog
    {
        public int ID { get; set; }
        public int USERID { get; set; }
        public System.DateTime OperateTime { get; set; }
        public Nullable<int> manipulationID { get; set; }
        public Nullable<int> Params1 { get; set; }
        public Nullable<int> Params2 { get; set; }
        public Nullable<int> Params3 { get; set; }
        public Nullable<int> Params4 { get; set; }
        public string SensorId { get; set; }
    }
}
