//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLIDAY
    {
        public int HOLIDAYID { get; set; }
        public string HOLIDAYNAME { get; set; }
        public Nullable<short> HOLIDAYYEAR { get; set; }
        public Nullable<short> HOLIDAYMONTH { get; set; }
        public Nullable<short> HOLIDAYDAY { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<short> DURATION { get; set; }
        public Nullable<short> HOLIDAYTYPE { get; set; }
        public string XINBIE { get; set; }
        public string MINZU { get; set; }
        public Nullable<short> DeptID { get; set; }
    }
}
