//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUM_RUN_DEIL
    {
        public short NUM_RUNID { get; set; }
        public System.DateTime STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public short SDAYS { get; set; }
        public Nullable<short> EDAYS { get; set; }
        public Nullable<int> SCHCLASSID { get; set; }
        public Nullable<int> OverTime { get; set; }
    }
}
