//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchClass
    {
        public int schClassid { get; set; }
        public string schName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> EarlyMinutes { get; set; }
        public Nullable<int> CheckIn { get; set; }
        public Nullable<int> CheckOut { get; set; }
        public Nullable<System.DateTime> CheckInTime1 { get; set; }
        public Nullable<System.DateTime> CheckInTime2 { get; set; }
        public Nullable<System.DateTime> CheckOutTime1 { get; set; }
        public Nullable<System.DateTime> CheckOutTime2 { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<short> AutoBind { get; set; }
        public Nullable<double> WorkDay { get; set; }
        public string SensorID { get; set; }
        public Nullable<double> WorkMins { get; set; }
    }
}
