//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITYDETAIL
    {
        public int SECURITYDETAILID { get; set; }
        public Nullable<short> USERID { get; set; }
        public Nullable<short> DEPTID { get; set; }
        public Nullable<short> SCHEDULE { get; set; }
        public Nullable<short> USERINFO { get; set; }
        public Nullable<short> ENROLLFINGERS { get; set; }
        public Nullable<short> REPORTVIEW { get; set; }
        public string REPORT { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public Nullable<bool> FullControl { get; set; }
    }
}
