//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIUKEntities : DbContext
    {
        public SIUKEntities()
            : base("name=SIUKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<V_LIST_HARI_LIBUR> V_LIST_HARI_LIBUR { get; set; }
        public DbSet<V_LIST_SDM> V_LIST_SDM { get; set; }
    }
}
