//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int ID { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string MachineAlias { get; set; }
        public Nullable<short> LogTag { get; set; }
        public string LogDescr { get; set; }
    }
}
