//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSMSINFO
    {
        public int REFERENCE { get; set; }
        public string SMSID { get; set; }
        public int SMSINDEX { get; set; }
        public Nullable<int> SMSTYPE { get; set; }
        public string SMSCONTENT { get; set; }
        public string SMSSTARTTM { get; set; }
        public Nullable<int> SMSTMLENG { get; set; }
        public string GENTM { get; set; }
    }
}
