//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSMSALLOT
    {
        public int REFERENCE { get; set; }
        public int SMSREF { get; set; }
        public int USERREF { get; set; }
        public string GENTM { get; set; }
    }
}
