//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPLATE
    {
        public int TEMPLATEID { get; set; }
        public int USERID { get; set; }
        public int FINGERID { get; set; }
        public byte[] TEMPLATE1 { get; set; }
        public byte[] TEMPLATE2 { get; set; }
        public byte[] TEMPLATE3 { get; set; }
        public byte[] BITMAPPICTURE { get; set; }
        public byte[] BITMAPPICTURE2 { get; set; }
        public byte[] BITMAPPICTURE3 { get; set; }
        public byte[] BITMAPPICTURE4 { get; set; }
        public Nullable<short> USETYPE { get; set; }
        public string EMACHINENUM { get; set; }
        public byte[] TEMPLATE11 { get; set; }
        public Nullable<short> Flag { get; set; }
        public Nullable<short> DivisionFP { get; set; }
        public byte[] TEMPLATE4 { get; set; }
    }
}
