//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SPEDAY
    {
        public int USERID { get; set; }
        public System.DateTime STARTSPECDAY { get; set; }
        public Nullable<System.DateTime> ENDSPECDAY { get; set; }
        public short DATEID { get; set; }
        public string YUANYING { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
