//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_OF_RUN
    {
        public int USERID { get; set; }
        public int NUM_OF_RUN_ID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public Nullable<int> ISNOTOF_RUN { get; set; }
        public Nullable<int> ORDER_RUN { get; set; }
    }
}
