//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserACPrivilege
    {
        public int UserID { get; set; }
        public short ACGroupID { get; set; }
        public Nullable<bool> IsUseGroup { get; set; }
        public Nullable<short> TimeZone1 { get; set; }
        public Nullable<short> TimeZone2 { get; set; }
        public Nullable<short> TimeZone3 { get; set; }
    }
}
