//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LIST_HARI_LIBUR
    {
        public System.DateTime TGL_LIBUR { get; set; }
        public string KETERANGAN { get; set; }
        public string STS_KD_KLP { get; set; }
        public string STS_KODE { get; set; }
    }
}
