//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LIST_SDM
    {
        public string NRK { get; set; }
        public string KD_DIT { get; set; }
        public string NAMA_DIT { get; set; }
        public string KD_SUB { get; set; }
        public string NAMA_SUB { get; set; }
        public string KD_SEK { get; set; }
        public string NAMA_SEK { get; set; }
        public string NAJAB { get; set; }
        public string NAMA { get; set; }
        public Nullable<decimal> P3 { get; set; }
        public Nullable<decimal> TTL { get; set; }
        public Nullable<decimal> PKWT { get; set; }
        public Nullable<short> KELAS { get; set; }
        public string KD_JNS_JABATAN { get; set; }
    }
}
