//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsensiTTL.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCheckInOut
    {
        public System.DateTime CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public int USERID { get; set; }
        public string BADGENUMBER { get; set; }
        public string NAME { get; set; }
    }
}
